/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardParentRouteImport } from './routes/dashboard.parent'
import { Route as DashboardStudentRouteImport } from './routes/dashboard.student'
import { Route as DashboardTeacherRouteImport } from './routes/dashboard.teacher'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard.admin.index'
import { Route as DashboardAdminCoursesRouteImport } from './routes/dashboard.admin.courses'
import { Route as DashboardAdminReportsRouteImport } from './routes/dashboard.admin.reports'
import { Route as DashboardAdminStudentsRouteImport } from './routes/dashboard.admin.students'
import { Route as DashboardAdminTeachersRouteImport } from './routes/dashboard.admin.teachers'
import { Route as DashboardTeacherIndexRouteImport } from './routes/dashboard.teacher.index'
import { Route as DashboardTeacherChatRouteImport } from './routes/dashboard.teacher.chat'
import { Route as DashboardTeacherExamsRouteImport } from './routes/dashboard.teacher.exams'
import { Route as DashboardTeacherGradescopeRouteImport } from './routes/dashboard.teacher.gradescope'
import { Route as DashboardTeacherGradingRouteImport } from './routes/dashboard.teacher.grading'
import { Route as DashboardTeacherImportRouteImport } from './routes/dashboard.teacher.import'
import { Route as DashboardTeacherLessonsRouteImport } from './routes/dashboard.teacher.lessons'
import { Route as DashboardTeacherLiveRouteImport } from './routes/dashboard.teacher.live'
import { Route as DashboardTeacherParentsRouteImport } from './routes/dashboard.teacher.parents'
import { Route as DashboardTeacherQuestionBankRouteImport } from './routes/dashboard.teacher.question-bank'
import { Route as DashboardTeacherQuizzesRouteImport } from './routes/dashboard.teacher.quizzes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardParentRoute = DashboardParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudentRoute = DashboardStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeacherRoute = DashboardTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminCoursesRoute = DashboardAdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminReportsRoute = DashboardAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminStudentsRoute = DashboardAdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminTeachersRoute = DashboardAdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardTeacherIndexRoute = DashboardTeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardTeacherRoute,
} as any)
const DashboardTeacherChatRoute = DashboardTeacherChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardTeacherRoute,
} as any)
const DashboardTeacherExamsRoute = DashboardTeacherExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => DashboardTeacherRoute,
} as any)
const DashboardTeacherGradescopeRoute =
  DashboardTeacherGradescopeRouteImport.update({
    id: '/gradescope',
    path: '/gradescope',
    getParentRoute: () => DashboardTeacherRoute,
  } as any)
const DashboardTeacherGradingRoute = DashboardTeacherGradingRouteImport.update({
  id: '/grading',
  path: '/grading',
  getParentRoute: () => DashboardTeacherRoute,
} as any)
const DashboardTeacherImportRoute = DashboardTeacherImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => DashboardTeacherRoute,
} as any)
const DashboardTeacherLessonsRoute = DashboardTeacherLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => DashboardTeacherRoute,
} as any)
const DashboardTeacherLiveRoute = DashboardTeacherLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => DashboardTeacherRoute,
} as any)
const DashboardTeacherParentsRoute = DashboardTeacherParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => DashboardTeacherRoute,
} as any)
const DashboardTeacherQuestionBankRoute =
  DashboardTeacherQuestionBankRouteImport.update({
    id: '/question-bank',
    path: '/question-bank',
    getParentRoute: () => DashboardTeacherRoute,
  } as any)
const DashboardTeacherQuizzesRoute = DashboardTeacherQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => DashboardTeacherRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/parent': typeof DashboardParentRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/dashboard/teacher': typeof DashboardTeacherRouteWithChildren
  '/courses/': typeof CoursesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/courses': typeof DashboardAdminCoursesRoute
  '/dashboard/admin/reports': typeof DashboardAdminReportsRoute
  '/dashboard/admin/students': typeof DashboardAdminStudentsRoute
  '/dashboard/admin/teachers': typeof DashboardAdminTeachersRoute
  '/dashboard/teacher/chat': typeof DashboardTeacherChatRoute
  '/dashboard/teacher/exams': typeof DashboardTeacherExamsRoute
  '/dashboard/teacher/gradescope': typeof DashboardTeacherGradescopeRoute
  '/dashboard/teacher/grading': typeof DashboardTeacherGradingRoute
  '/dashboard/teacher/import': typeof DashboardTeacherImportRoute
  '/dashboard/teacher/lessons': typeof DashboardTeacherLessonsRoute
  '/dashboard/teacher/live': typeof DashboardTeacherLiveRoute
  '/dashboard/teacher/parents': typeof DashboardTeacherParentsRoute
  '/dashboard/teacher/question-bank': typeof DashboardTeacherQuestionBankRoute
  '/dashboard/teacher/quizzes': typeof DashboardTeacherQuizzesRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/teacher/': typeof DashboardTeacherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/dashboard/parent': typeof DashboardParentRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/courses': typeof CoursesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/courses': typeof DashboardAdminCoursesRoute
  '/dashboard/admin/reports': typeof DashboardAdminReportsRoute
  '/dashboard/admin/students': typeof DashboardAdminStudentsRoute
  '/dashboard/admin/teachers': typeof DashboardAdminTeachersRoute
  '/dashboard/teacher/chat': typeof DashboardTeacherChatRoute
  '/dashboard/teacher/exams': typeof DashboardTeacherExamsRoute
  '/dashboard/teacher/gradescope': typeof DashboardTeacherGradescopeRoute
  '/dashboard/teacher/grading': typeof DashboardTeacherGradingRoute
  '/dashboard/teacher/import': typeof DashboardTeacherImportRoute
  '/dashboard/teacher/lessons': typeof DashboardTeacherLessonsRoute
  '/dashboard/teacher/live': typeof DashboardTeacherLiveRoute
  '/dashboard/teacher/parents': typeof DashboardTeacherParentsRoute
  '/dashboard/teacher/question-bank': typeof DashboardTeacherQuestionBankRoute
  '/dashboard/teacher/quizzes': typeof DashboardTeacherQuizzesRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/teacher': typeof DashboardTeacherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/parent': typeof DashboardParentRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/dashboard/teacher': typeof DashboardTeacherRouteWithChildren
  '/courses/': typeof CoursesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/courses': typeof DashboardAdminCoursesRoute
  '/dashboard/admin/reports': typeof DashboardAdminReportsRoute
  '/dashboard/admin/students': typeof DashboardAdminStudentsRoute
  '/dashboard/admin/teachers': typeof DashboardAdminTeachersRoute
  '/dashboard/teacher/chat': typeof DashboardTeacherChatRoute
  '/dashboard/teacher/exams': typeof DashboardTeacherExamsRoute
  '/dashboard/teacher/gradescope': typeof DashboardTeacherGradescopeRoute
  '/dashboard/teacher/grading': typeof DashboardTeacherGradingRoute
  '/dashboard/teacher/import': typeof DashboardTeacherImportRoute
  '/dashboard/teacher/lessons': typeof DashboardTeacherLessonsRoute
  '/dashboard/teacher/live': typeof DashboardTeacherLiveRoute
  '/dashboard/teacher/parents': typeof DashboardTeacherParentsRoute
  '/dashboard/teacher/question-bank': typeof DashboardTeacherQuestionBankRoute
  '/dashboard/teacher/quizzes': typeof DashboardTeacherQuizzesRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/teacher/': typeof DashboardTeacherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/courses/$courseId'
    | '/dashboard/admin'
    | '/dashboard/parent'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/courses/'
    | '/dashboard/'
    | '/dashboard/admin/courses'
    | '/dashboard/admin/reports'
    | '/dashboard/admin/students'
    | '/dashboard/admin/teachers'
    | '/dashboard/teacher/chat'
    | '/dashboard/teacher/exams'
    | '/dashboard/teacher/gradescope'
    | '/dashboard/teacher/grading'
    | '/dashboard/teacher/import'
    | '/dashboard/teacher/lessons'
    | '/dashboard/teacher/live'
    | '/dashboard/teacher/parents'
    | '/dashboard/teacher/question-bank'
    | '/dashboard/teacher/quizzes'
    | '/dashboard/admin/'
    | '/dashboard/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/courses/$courseId'
    | '/dashboard/parent'
    | '/dashboard/student'
    | '/courses'
    | '/dashboard'
    | '/dashboard/admin/courses'
    | '/dashboard/admin/reports'
    | '/dashboard/admin/students'
    | '/dashboard/admin/teachers'
    | '/dashboard/teacher/chat'
    | '/dashboard/teacher/exams'
    | '/dashboard/teacher/gradescope'
    | '/dashboard/teacher/grading'
    | '/dashboard/teacher/import'
    | '/dashboard/teacher/lessons'
    | '/dashboard/teacher/live'
    | '/dashboard/teacher/parents'
    | '/dashboard/teacher/question-bank'
    | '/dashboard/teacher/quizzes'
    | '/dashboard/admin'
    | '/dashboard/teacher'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/courses/$courseId'
    | '/dashboard/admin'
    | '/dashboard/parent'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/courses/'
    | '/dashboard/'
    | '/dashboard/admin/courses'
    | '/dashboard/admin/reports'
    | '/dashboard/admin/students'
    | '/dashboard/admin/teachers'
    | '/dashboard/teacher/chat'
    | '/dashboard/teacher/exams'
    | '/dashboard/teacher/gradescope'
    | '/dashboard/teacher/grading'
    | '/dashboard/teacher/import'
    | '/dashboard/teacher/lessons'
    | '/dashboard/teacher/live'
    | '/dashboard/teacher/parents'
    | '/dashboard/teacher/question-bank'
    | '/dashboard/teacher/quizzes'
    | '/dashboard/admin/'
    | '/dashboard/teacher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/parent': {
      id: '/dashboard/parent'
      path: '/parent'
      fullPath: '/dashboard/parent'
      preLoaderRoute: typeof DashboardParentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/student': {
      id: '/dashboard/student'
      path: '/student'
      fullPath: '/dashboard/student'
      preLoaderRoute: typeof DashboardStudentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/teacher': {
      id: '/dashboard/teacher'
      path: '/teacher'
      fullPath: '/dashboard/teacher'
      preLoaderRoute: typeof DashboardTeacherRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/courses': {
      id: '/dashboard/admin/courses'
      path: '/courses'
      fullPath: '/dashboard/admin/courses'
      preLoaderRoute: typeof DashboardAdminCoursesRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/reports': {
      id: '/dashboard/admin/reports'
      path: '/reports'
      fullPath: '/dashboard/admin/reports'
      preLoaderRoute: typeof DashboardAdminReportsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/students': {
      id: '/dashboard/admin/students'
      path: '/students'
      fullPath: '/dashboard/admin/students'
      preLoaderRoute: typeof DashboardAdminStudentsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/teachers': {
      id: '/dashboard/admin/teachers'
      path: '/teachers'
      fullPath: '/dashboard/admin/teachers'
      preLoaderRoute: typeof DashboardAdminTeachersRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/teacher/': {
      id: '/dashboard/teacher/'
      path: '/'
      fullPath: '/dashboard/teacher/'
      preLoaderRoute: typeof DashboardTeacherIndexRouteImport
      parentRoute: typeof DashboardTeacherRoute
    }
    '/dashboard/teacher/chat': {
      id: '/dashboard/teacher/chat'
      path: '/chat'
      fullPath: '/dashboard/teacher/chat'
      preLoaderRoute: typeof DashboardTeacherChatRouteImport
      parentRoute: typeof DashboardTeacherRoute
    }
    '/dashboard/teacher/exams': {
      id: '/dashboard/teacher/exams'
      path: '/exams'
      fullPath: '/dashboard/teacher/exams'
      preLoaderRoute: typeof DashboardTeacherExamsRouteImport
      parentRoute: typeof DashboardTeacherRoute
    }
    '/dashboard/teacher/gradescope': {
      id: '/dashboard/teacher/gradescope'
      path: '/gradescope'
      fullPath: '/dashboard/teacher/gradescope'
      preLoaderRoute: typeof DashboardTeacherGradescopeRouteImport
      parentRoute: typeof DashboardTeacherRoute
    }
    '/dashboard/teacher/grading': {
      id: '/dashboard/teacher/grading'
      path: '/grading'
      fullPath: '/dashboard/teacher/grading'
      preLoaderRoute: typeof DashboardTeacherGradingRouteImport
      parentRoute: typeof DashboardTeacherRoute
    }
    '/dashboard/teacher/import': {
      id: '/dashboard/teacher/import'
      path: '/import'
      fullPath: '/dashboard/teacher/import'
      preLoaderRoute: typeof DashboardTeacherImportRouteImport
      parentRoute: typeof DashboardTeacherRoute
    }
    '/dashboard/teacher/lessons': {
      id: '/dashboard/teacher/lessons'
      path: '/lessons'
      fullPath: '/dashboard/teacher/lessons'
      preLoaderRoute: typeof DashboardTeacherLessonsRouteImport
      parentRoute: typeof DashboardTeacherRoute
    }
    '/dashboard/teacher/live': {
      id: '/dashboard/teacher/live'
      path: '/live'
      fullPath: '/dashboard/teacher/live'
      preLoaderRoute: typeof DashboardTeacherLiveRouteImport
      parentRoute: typeof DashboardTeacherRoute
    }
    '/dashboard/teacher/parents': {
      id: '/dashboard/teacher/parents'
      path: '/parents'
      fullPath: '/dashboard/teacher/parents'
      preLoaderRoute: typeof DashboardTeacherParentsRouteImport
      parentRoute: typeof DashboardTeacherRoute
    }
    '/dashboard/teacher/question-bank': {
      id: '/dashboard/teacher/question-bank'
      path: '/question-bank'
      fullPath: '/dashboard/teacher/question-bank'
      preLoaderRoute: typeof DashboardTeacherQuestionBankRouteImport
      parentRoute: typeof DashboardTeacherRoute
    }
    '/dashboard/teacher/quizzes': {
      id: '/dashboard/teacher/quizzes'
      path: '/quizzes'
      fullPath: '/dashboard/teacher/quizzes'
      preLoaderRoute: typeof DashboardTeacherQuizzesRouteImport
      parentRoute: typeof DashboardTeacherRoute
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminCoursesRoute: typeof DashboardAdminCoursesRoute
  DashboardAdminReportsRoute: typeof DashboardAdminReportsRoute
  DashboardAdminStudentsRoute: typeof DashboardAdminStudentsRoute
  DashboardAdminTeachersRoute: typeof DashboardAdminTeachersRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminCoursesRoute: DashboardAdminCoursesRoute,
  DashboardAdminReportsRoute: DashboardAdminReportsRoute,
  DashboardAdminStudentsRoute: DashboardAdminStudentsRoute,
  DashboardAdminTeachersRoute: DashboardAdminTeachersRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardTeacherRouteChildren {
  DashboardTeacherChatRoute: typeof DashboardTeacherChatRoute
  DashboardTeacherExamsRoute: typeof DashboardTeacherExamsRoute
  DashboardTeacherGradescopeRoute: typeof DashboardTeacherGradescopeRoute
  DashboardTeacherGradingRoute: typeof DashboardTeacherGradingRoute
  DashboardTeacherImportRoute: typeof DashboardTeacherImportRoute
  DashboardTeacherLessonsRoute: typeof DashboardTeacherLessonsRoute
  DashboardTeacherLiveRoute: typeof DashboardTeacherLiveRoute
  DashboardTeacherParentsRoute: typeof DashboardTeacherParentsRoute
  DashboardTeacherQuestionBankRoute: typeof DashboardTeacherQuestionBankRoute
  DashboardTeacherQuizzesRoute: typeof DashboardTeacherQuizzesRoute
  DashboardTeacherIndexRoute: typeof DashboardTeacherIndexRoute
}

const DashboardTeacherRouteChildren: DashboardTeacherRouteChildren = {
  DashboardTeacherChatRoute: DashboardTeacherChatRoute,
  DashboardTeacherExamsRoute: DashboardTeacherExamsRoute,
  DashboardTeacherGradescopeRoute: DashboardTeacherGradescopeRoute,
  DashboardTeacherGradingRoute: DashboardTeacherGradingRoute,
  DashboardTeacherImportRoute: DashboardTeacherImportRoute,
  DashboardTeacherLessonsRoute: DashboardTeacherLessonsRoute,
  DashboardTeacherLiveRoute: DashboardTeacherLiveRoute,
  DashboardTeacherParentsRoute: DashboardTeacherParentsRoute,
  DashboardTeacherQuestionBankRoute: DashboardTeacherQuestionBankRoute,
  DashboardTeacherQuizzesRoute: DashboardTeacherQuizzesRoute,
  DashboardTeacherIndexRoute: DashboardTeacherIndexRoute,
}

const DashboardTeacherRouteWithChildren =
  DashboardTeacherRoute._addFileChildren(DashboardTeacherRouteChildren)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardParentRoute: typeof DashboardParentRoute
  DashboardStudentRoute: typeof DashboardStudentRoute
  DashboardTeacherRoute: typeof DashboardTeacherRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardParentRoute: DashboardParentRoute,
  DashboardStudentRoute: DashboardStudentRoute,
  DashboardTeacherRoute: DashboardTeacherRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
